export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'The first blog',
        author: 'author1',
        dateStr: 'May 12nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog1.html',
      },
      {
        title: 'The second blog',
        author: 'author2',
        dateStr: 'May 2nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog2.html',
      },
      {
        title: 'The third blog',
        author: 'author3',
        dateStr: 'April 25th，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog3.html',
      },
      {
        title: 'The forth blog',
        author: 'author4',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog4.html',
      },
      {
        title: 'The fifth blog',
        author: 'author5',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog5.html',
      },
      {
        title: 'The sixth blog',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog6.html',
      },
      {
        title: 'The seventh blog',
        author: 'author7',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog7.html',
      },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: '4.0.0版本发布',
        author: '凯京科技',
        dateStr: 'Jul 6th 2021',
        desc: 'kkFileView v4.0.0 发布，文件文档在线预览解决方案',
        link: 'https://www.oschina.net/news/149206/kkfileview-4-0-released',
        target: '_blank',
      },
      {
        title: '3.6.0版本发布',
        author: '凯京科技',
        dateStr: 'Jun 17th 2021',
        desc: 'kkFileView 文件预览 ofd 支持版发布',
        link: 'https://www.oschina.net/news/146438/kkfileview-3-6-0-released',
        target: '_blank',
      },
      {
        title: '3.5.0版本发布',
        author: '凯京科技',
        dateStr: 'Mar 19th 2021',
        desc: 'kkFileView 文件预览 v3.5 性能升级版发布',
        link: 'https://www.oschina.net/news/133737/kkfileview-3-5-released',
        target: '_blank',
      },
      {
        title: '3.3.1版本发布',
        author: '凯京科技',
        dateStr: 'Jan 28th 2021',
        desc: 'kkFileView 文件预览 v3.3.1 岁末版本发布',
        link: 'https://www.oschina.net/news/128117/kkfileview-3-3-1-released',
        target: '_blank',
      },
      {
        title: '3.3.0版本发布',
        author: '凯京科技',
        dateStr: 'Dec 27th 2020',
        desc: 'kkFileView-v3.3.0 年终版本发布，架构功能全面升级',
        link: 'https://www.oschina.net/news/124748/kkfileview-3-3-0-released',
        target: '_blank',
      },
      {
        title: '2.2.1版本发布',
        author: '凯京科技',
        dateStr: 'Aug 12th 2020',
        desc: 'kkFileView v2.2.1 发布，文件文档在线预览解决方案',
        link: 'https://www.oschina.net/news/117869/kkfileview-2-2-1-released',
        target: '_blank',
      },
      {
        title: '2.2.0版本发布',
        author: '凯京科技',
        dateStr: 'May 20th 2020',
        desc: 'kkFileView v2.2.0 发布，文件文档在线预览解决方案',
        link: 'https://www.oschina.net/news/115789/kkfileview-2-2-0-released',
        target: '_blank',
      },
      {
        title: '2.1.1版本发布',
        author: '凯京科技',
        dateStr: 'Jul 9th，2019',
        desc: 'kkFileView v2.1.1 发布，文件文档在线预览解决方案',
        link: 'https://www.oschina.net/news/108101/kkfileview-2-1-1-released',
        target: '_blank',
      },
      {
        title: '2.1.0版本发布',
        author: '凯京科技',
        dateStr: 'Jun 24th，2019',
        desc: 'kkFileView v2.1.0 发布，文件文档在线预览解决方案',
        link: 'https://www.oschina.net/news/107681/kkfileview-2-1-0-released',
        target: '_blank',
      },
      {
        title: '2.0版本发布',
        author: '凯京科技',
        dateStr: 'May 7th，2019',
        desc: 'kkfileview v2.0 发布，文件在线预览项目方案',
        link: 'https://www.oschina.net/news/106499/kkfileview-2-0-released',
        target: '_blank',
      },
      {
        title: '年终答疑',
        author: 'kl',
        dateStr: 'Jan 31th，2019',
        desc: 'kkfileView使用问题年终答疑篇',
        link: 'https://my.oschina.net/keking/blog/3007867',
        target: '_blank',
      },
      {
        title: '1.1版本发布',
        author: '凯京科技',
        dateStr: 'Mar 25th，2018',
        desc: '文件预览 kkFileView v1.1 新增多媒体预览支持等',
        link: 'https://www.oschina.net/news/94561/kkfileview-1-1-released',
        target: '_blank',
      },
      {
        title: '安全问题',
        author: '凯京科技',
        dateStr: 'Mar 16th，2018',
        desc: '关于使用 KKFileView 体验服务带来的安全问题',
        link: 'https://www.oschina.net/news/94273/kkfileview-security-announcement',
        target: '_blank',
      },
      {
        title: '更名kkFileView',
        author: '凯京科技',
        dateStr: 'Jan 17th，2018',
        desc: 'file-online-previe 更名 kkFileView 向全能的文件预览迈进',
        link: 'https://www.oschina.net/news/92518/kkfileview-1-0-released',
        target: '_blank',
      },
      {
        title: '首个发行版',
        author: '凯京科技',
        dateStr: 'Jan 2nd，2018',
        desc: 'file-online-preview v0.0.2 首个发行版，不断改进中',
        link: 'https://www.oschina.net/news/92062/file-online-preview-0-0-2',
        target: '_blank',
      },
    ],
  },
};
